export const pendingStudents = [
    {
      id: "STU-1001",
      name: "Alex Johnson",
      email: "alex.johnson@university.edu",
      department: "Computer Science",
      registrationDate: "2023-05-15",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      id: "STU-1002",
      name: "Samantha Lee",
      email: "samantha.lee@university.edu",
      department: "Electrical Engineering",
      registrationDate: "2023-05-16",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      id: "STU-1003",
      name: "Michael Chen",
      email: "michael.chen@university.edu",
      department: "Mechanical Engineering",
      registrationDate: "2023-05-17",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      id: "STU-1004",
      name: "Emily Wilson",
      email: "emily.wilson@university.edu",
      department: "Computer Science",
      registrationDate: "2023-05-18",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      id: "STU-1005",
      name: "David Kim",
      email: "david.kim@university.edu",
      department: "Physics",
      registrationDate: "2023-05-19",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  ]
  
  export const pendingTeachers = [
    {
      id: "TCH-2001",
      name: "Dr. Sarah Johnson",
      email: "sarah.johnson@university.edu",
      department: "Computer Science",
      specialization: "Artificial Intelligence",
      registrationDate: "2023-05-10",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      id: "TCH-2002",
      name: "Prof. Robert Chen",
      email: "robert.chen@university.edu",
      department: "Electrical Engineering",
      specialization: "Robotics",
      registrationDate: "2023-05-11",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      id: "TCH-2003",
      name: "Dr. Lisa Wang",
      email: "lisa.wang@university.edu",
      department: "Physics",
      specialization: "Quantum Computing",
      registrationDate: "2023-05-12",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  ]
  
  export const pendingProjects = [
    {
      id: "PRJ-3001",
      title: "AI-Powered Student Feedback System",
      description: "A system that uses AI to provide automated feedback on student assignments and projects.",
      submittedBy: "Alex Johnson",
      supervisor: "Dr. Sarah Johnson",
      department: "Computer Science",
      submissionDate: "2023-05-20",
    },
    {
      id: "PRJ-3002",
      title: "Sustainable Urban Planning Model",
      description: "A model that uses data analytics to optimize urban planning for sustainability and efficiency.",
      submittedBy: "Samantha Lee",
      supervisor: "Prof. Robert Chen",
      department: "Civil Engineering",
      submissionDate: "2023-05-21",
    },
    {
      id: "PRJ-3003",
      title: "Quantum Computing Algorithm for Drug Discovery",
      description: "An algorithm that leverages quantum computing to accelerate drug discovery processes.",
      submittedBy: "Michael Chen",
      supervisor: "Dr. Lisa Wang",
      department: "Physics",
      submissionDate: "2023-05-22",
    },
    {
      id: "PRJ-3004",
      title: "Renewable Energy Grid Optimization",
      description: "A project focused on optimizing energy distribution in grids powered by renewable sources.",
      submittedBy: "Emily Wilson",
      supervisor: "Prof. Robert Chen",
      department: "Electrical Engineering",
      submissionDate: "2023-05-23",
    },
    {
      id: "PRJ-3005",
      title: "Machine Learning for Climate Prediction",
      description: "Using machine learning models to improve climate change prediction accuracy.",
      submittedBy: "David Kim",
      supervisor: "Dr. Lisa Wang",
      department: "Environmental Science",
      submissionDate: "2023-05-24",
    },
  ]
  
  export const approvalHistory = [
    {
      id: "STU-1000",
      name: "Jessica Parker",
      type: "Student",
      action: "Approved",
      date: "2023-05-14",
      approvedBy: "Admin",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      id: "TCH-2000",
      name: "Dr. James Wilson",
      type: "Teacher",
      action: "Approved",
      date: "2023-05-09",
      approvedBy: "Admin",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      id: "PRJ-3000",
      name: "Blockchain for Academic Records",
      type: "Project",
      action: "Rejected",
      date: "2023-05-19",
      approvedBy: "Admin",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      id: "STU-999",
      name: "Thomas Brown",
      type: "Student",
      action: "Approved",
      date: "2023-05-13",
      approvedBy: "Admin",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      id: "PRJ-2999",
      name: "Virtual Reality Learning Environment",
      type: "Project",
      action: "Approved",
      date: "2023-05-18",
      approvedBy: "Admin",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  ]


  